name: faqchatbot
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.3.5=py310h9128911_0
  - brotlipy=0.7.0=py310he2412df_1004
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2022.12.7=h5b45459_0
  - catalogue=2.0.8=py310h5588dad_1
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310hcbf9ad4_0
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - click=8.0.4=py310haa95532_0
  - colorama=0.4.6=py310haa95532_0
  - cryptography=3.4.8=py310ha857299_1
  - cymem=2.0.6=py310hd77b12b_0
  - cython-blis=0.7.7=py310h9128911_0
  - fftw=3.3.9=h2bbff1b_1
  - flask=2.2.2=py310haa95532_0
  - gensim=4.3.0=py310h4ed8f06_0
  - icc_rt=2022.1.0=h6049295_2
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=haa95532_3556
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jinja2=3.1.2=py310haa95532_0
  - joblib=1.1.1=py310haa95532_0
  - langcodes=3.3.0=pyhd8ed1ab_0
  - libffi=3.4.2=hd77b12b_6
  - markupsafe=2.1.1=py310h2bbff1b_0
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py310h2bbff1b_0
  - mkl_fft=1.3.1=py310ha0764ea_0
  - mkl_random=1.2.2=py310h4ed8f06_0
  - murmurhash=1.0.7=py310hd77b12b_0
  - nltk=3.7=pyhd3eb1b0_0
  - numexpr=2.8.4=py310hd213c9f_0
  - numpy=1.23.5=py310h60c9a35_0
  - numpy-base=1.23.5=py310h04254f7_0
  - openssl=1.1.1t=h2bbff1b_0
  - packaging=22.0=py310haa95532_0
  - pandas=1.5.2=py310h4ed8f06_0
  - pathy=0.10.1=py310haa95532_0
  - pip=23.0.1=py310haa95532_0
  - preshed=3.0.6=py310h6c2663c_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.10.11=h966fe2a_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytz=2022.7=py310haa95532_0
  - regex=2022.7.9=py310h2bbff1b_0
  - requests=2.28.2=pyhd8ed1ab_1
  - scikit-learn=1.2.0=py310hd77b12b_1
  - scipy=1.9.3=py310h86744a3_0
  - setuptools=66.0.0=py310haa95532_0
  - shellingham=1.5.1=pyhd8ed1ab_0
  - six=1.16.0=pyhd3eb1b0_1
  - smart_open=6.3.0=pyhd8ed1ab_1
  - spacy=3.3.1=py310hef0f399_0
  - spacy-legacy=3.0.12=pyhd8ed1ab_0
  - spacy-loggers=1.0.4=pyhd8ed1ab_0
  - sqlite=3.41.2=h2bbff1b_0
  - srsly=2.4.6=py310hd77b12b_0
  - thinc=8.0.15=py310hf497b98_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h2bbff1b_0
  - tqdm=4.64.1=py310haa95532_0
  - typer=0.4.2=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wasabi=0.10.1=pyhd8ed1ab_1
  - werkzeug=2.2.2=py310haa95532_0
  - wheel=0.38.4=py310haa95532_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - xz=5.2.10=h8cc25b3_1
  - zlib=1.2.13=h8cc25b3_0
  - pip:
      - absl-py==1.4.0
      - astunparse==1.6.3
      - bert-serving-client==1.10.0
      - bert-serving-server==1.10.0
      - cachetools==5.3.0
      - en-core-web-sm==3.3.0
      - faiss-cpu===1.7.4
      - flatbuffers==23.3.3
      - gast==0.4.0
      - google-auth==2.17.3
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - gputil==1.4.0
      - grpcio==1.54.0
      - h5py==3.8.0
      - jax==0.4.8
      - keras==2.12.0
      - libclang==16.0.0
      - markdown==3.4.3
      - ml-dtypes==0.1.0
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - protobuf==4.22.3
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydantic==1.8.2
      - python-version==0.0.2
      - pyzmq==25.0.2
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - tensorboard==2.12.2
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.12.0
      - tensorflow-estimator==2.12.0
      - tensorflow-intel==2.12.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.2.0
      - wrapt==1.14.1
      - langchain==0.0.150
		  - openai==0.27.4
		  - openapi-schema-pydantic==1.2.4
		  - tiktoken==0.3.3
prefix: C:\Users\yoges\anaconda3\envs\faqchatbot
